build-job: 
  stage: build
  tags: 
    - spm-backend
  script:
    - docker build -t lingliyin/spm-backend:latest .
    - docker image push lingliyin/spm-backend:latest

  stage: test 
  script: 
    - python lms/classes_integration_test.py
    - python lms/courses_integration_test.py
    - python lms/lessons_integration_test.py
    - python lms/users_integration_test.py

  stage: deploy 
  rules: 
    - if: '$CI_COMMIT_REF_NAME == "SPMG6T9-75-cicd"'
  script: 
    - aws ecs update-task-definition
    # - aws ecs update-service --cluster spm-backend-cluster --service spm-backend-service --force-new-deployment