stages:
    - build
    - test
    - deploy

docker-build:
  stage: build
  tags: 
    - spm-backend
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t registry.gitlab.com/liyin001/spm-backend .
    - docker push registry.gitlab.com/liyin001/spm-backend

scripts-test:
  stage: test 
  script: 
    - pip install requirements.txt
    - python classes_integration_test.py
    - python courses_integration_test.py
    - python lessons_integration_test.py
    - python users_integration_test.py

deploy-ecs:
  stage: deploy 
  rules: 
    - if: '$CI_COMMIT_REF_NAME == "SPMG6T9-75-cicd"'
  script: 
    # - aws ecs update-task-definition
    - aws ecs update-service --cluster liyin-spm --service spm-backend --force-new-deployment
    # - aws ecs update-service --force-new-deployment