# before_script:
#   - apt-get install -y python-pip 
#   - pip install -r requirements.txt

stages:
    - test
    - build
    - deploy

test: 
  stage: test
  image: python:3.6
  tags: 
    - github-org
  before_script:
    - apt-get update -q -y 
    - apt-get install -y python-pip 
    - python -V
    - pip install -r requirements.txt
  script:
    - python classes_integration_test.py 


build:
  stage: build
  image: docker:latest 
  tags: 
    - docker
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t registry.gitlab.com/liyin001/spm-backend .
    - docker push registry.gitlab.com/liyin001/spm-backend

deploy:
  stage: deploy 
  tags: 
    - linux 
  image: registry.gitlab.com/liyin001/spm-backend:latest
  rules: 
    - if: '$CI_COMMIT_REF_NAME == "SPMG6T9-75-cicd"'
  script: 
    - aws ecs update-service --cluster liyin-spm --service spm-backend --force-new-deployment

# scripts-test:
#   stage: test 
#   script: 
#     - python-pip install -r requirements.txt
#     - python classes_integration_test.py
#     - python courses_integration_test.py
#     - python lessons_integration_test.py
#     - python users_integration_test.py

# deploy-ecs:
#   stage: deploy 
#   rules: 
#     - if: '$CI_COMMIT_REF_NAME == "SPMG6T9-75-cicd"'
#   script: 
#     # - aws ecs update-task-definition
#     - aws ecs update-service --cluster liyin-spm --service spm-backend --force-new-deployment
    # - aws ecs update-service --force-new-deployment